version: "3"
services:
  axolotl:
    build: ./axolotl
    image: axolotl:27.7
    container_name: axolotl
    depends_on:
      - mongo
    restart: always
    env_file: .env
    networks:
      - frontend

networks: 
  frontend:
    external:
      name: gazzy_server_frontend
