version: "3"
services:
  axolotl:
    build: .
    image: axolotl:15.3-dev
    container_name: axolotl
    depends_on:
      - mongo
    ports:
      - 80:80
      # add restart policy
      
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ~/db:/data/db
