version: "3"
services:
  axolotl:
    build: ./axolotl
    image: axolotl:16.3.2019
    container_name: axolotl
    restart: always
    env_file: .env
    networks:
      - frontend

networks: 
  frontend:
    external:
      name: gazzyserver_frontend
