version: "3"
services:
  axolotl:
    build: ./axolotl
    image: axolotl:21.3
    container_name: axolotl
    depends_on:
      - mongo
    restart: always
    env_file: .env
  
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ~/Axolotl/.db:/data/db
    restart: always
  
  nginx:
    build: ./nginx
    image: my-nginx:21.3
    container_name: nginx
    volumes:
      - ~/Axolotl/logs/nginx:/var/log/nginx
    depends_on:
      - axolotl
    ports:
      - 80:80
      - 443:443
    restart: always
